### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by Yaksinikos** [DrFair/WallPumps#1]
Version: 1.5 I guess
OS: Linux
Issue: ONI gives Error on start
Other Mods: all disabled
ONI: 361684

**Comment by DrFair** [comment]
Thanks for the report. I am not able to test this on linux myself at the moment, so any additional information would be very helpful.
If you can upload your log file into a gist or pastebin, I can probably figure out the problem and fix it.
You can find the log file at: ~/.config/unity3d/Klei/Oxygen Not Included/Player.log

**Comment by Yaksinikos** [comment]
Here we go; https://gist.github.com/Translator5/3d4518cc560909790367bc8b3ecb0544

** Linux systems are case sensitiv, may its the case as for mac and win it works :)

**Comment by DrFair** [comment]
Yea, it seems like it's something to do with loading the asset files. Even if it's case sensitive, that should not be a problem since everything is lowercase on my end. Do you have any problems with other mods that has assets? Mods like [Wireless Automation](https://steamcommunity.com/sharedfiles/filedetails/?id=1718226085) or [Flow Splitters](https://steamcommunity.com/sharedfiles/filedetails/?id=1718226085)?

**Comment by Yaksinikos** [comment]
I got it, the files are named "anims\fairliquidwallpump_kanim" & "anims\fairgaswallpump_kanim" 
while obviously they should be in folder "anims".
Fixed it for me manually by renaming and moving :)
It was about the installation / unpacking as I downloaded it on github & zipping & unpacking trans-OS (WIN to LIN and otherwise) is bit buggy using Engrampa.

So not your fault!

**Comment by DrFair** [comment]
No worries, glad you solved the issue :)
